# Clé et nom du projet
sonar.projectKey=my_first_project
sonar.projectName=my_first_project
sonar.projectVersion=1.0

# Dossier source à analyser
sonar.sources=.

# URL du serveur SonarQube
sonar.host.url=http://localhost:9000

# Token généré dans SonarQube
sonar.login=sqp_a5650805d47265555c2a87b1190c3de3ccaca175
