server {
    listen 80;

    # Route vers le front-end
    location / {
        proxy_pass http://frontend:3000;
    }

    # Route vers le service api
    location /api/ {
        proxy_pass http://api:3000/;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    # Route vers le service auth
    location /auth/ {
        proxy_pass http://auth:4000/;
        proxy_set_header Host $host;
    }
}
