worker_processes 1;

events { 
    worker_connections 1024; 
}

http {
    # --- 1. LOAD BALANCING (Service Commandes sur 2 instances) ---
    upstream orders_service {
        server host.docker.internal:4000;
        server host.docker.internal:4001;
    }

    upstream users_service {
        server host.docker.internal:4500; # Beddelha l' 4500 hna
    }

    upstream products_service {
        server host.docker.internal:5000;
    }

    upstream notifications_service {
        server host.docker.internal:4501; # Beddelha l' 4501 hna
    }

    server {
        listen 80;

        # --- 2. HEADERS CORS & PROXY CONFIG ---
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        
        # CORS Headers
        add_header 'Access-Control-Allow-Origin' '*' always;
        add_header 'Access-Control-Allow-Methods' 'GET, POST, PUT, DELETE, OPTIONS' always;
        add_header 'Access-Control-Allow-Headers' 'Authorization,Content-Type' always;

        # --- 3. ROUTING ---

        # Service Utilisateurs
        location /api/users {
            proxy_pass http://users_service;
        }

        # Service Produits
        location /api/products {
            proxy_pass http://products_service;
        }

        # Service Commandes (via Load Balancer)
        location /api/orders {
            proxy_pass http://orders_service;
        }

        # Service Notifications
        location /api/notifications {
            proxy_pass http://notifications_service;
        }
    }
}